# This is a Databricks asset bundle definition for readmebundlename.
# See https://docs.databricks.com/dev-tools/bundles/index.html for documentation.
bundle:
  name: rednadatabricks

# artifacts:
#   python_artifact:
#     type: whl
#     build: uv build --wheel

include:
  - Azure Databricks/Workflows/*.yml
  - Azure Databricks/Clusters/*.yml

targets:
  dev:
    # The default target uses 'mode: development' to create a development copy.
    # - Deployed resources get prefixed with '[dev my_user_name]'
    # - Any job schedules and triggers are paused by default.
    # See also https://docs.databricks.com/dev-tools/bundles/deployment-modes.html.
    mode: development
    default: true
    workspace:
      host: https://dbc-3d597f5a-4384.cloud.databricks.com

  prod:
    mode: production
    workspace:
      host: https://dbc-b151634a-0514.cloud.databricks.com
      # We explicitly deploy to /Workspace/Users/mvcharygenai@gmail.com to make sure we only have a single copy.
      #root_path: /Workspace/Users/mvcharygenai@gmail.com/.bundle/${bundle.name}/${bundle.target}
      #root_path: /Workspace/Repos/.bundle/${bundle.name}/${bundle.target}
      root_path: /Workspace/Shared/.bundle/${bundle.name}/${bundle.target}
      
    permissions:
      - user_name: perumoduraju@gmail.com
        level: CAN_MANAGE
